load("@rules_python//python:defs.bzl", "py_library")

package(default_visibility = ["//visibility:public"])

licenses(["notice"])

py_library(
    name = "finetuning",
    srcs = ["finetuning.py"],
    srcs_version = "PY3",
)
